from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CHOPPER(object):
    def setupUi(self, CHOPPER):
        CHOPPER.setObjectName("CHOPPER")
        CHOPPER.resize(1265, 862)
        CHOPPER.setMinimumSize(QtCore.QSize(1265, 862))
        CHOPPER.setMaximumSize(QtCore.QSize(1265, 862))
        self.radioButton = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton.setGeometry(QtCore.QRect(891, 82, 321, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_2.setGeometry(QtCore.QRect(891, 142, 201, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_3.setGeometry(QtCore.QRect(891, 112, 201, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_4.setGeometry(QtCore.QRect(891, 172, 141, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_5.setGeometry(QtCore.QRect(891, 202, 241, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_6.setGeometry(QtCore.QRect(891, 232, 161, 20))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_7.setGeometry(QtCore.QRect(891, 382, 241, 20))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_8.setGeometry(QtCore.QRect(891, 412, 231, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_9.setGeometry(QtCore.QRect(891, 352, 331, 20))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_10.setGeometry(QtCore.QRect(891, 262, 151, 20))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_11.setGeometry(QtCore.QRect(891, 322, 161, 20))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_12.setGeometry(QtCore.QRect(891, 292, 231, 20))
        self.radioButton_12.setObjectName("radioButton_12")
        self.label = QtWidgets.QLabel(CHOPPER)
        self.label.setGeometry(QtCore.QRect(530, 590, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CHOPPER)
        self.label_2.setGeometry(QtCore.QRect(542, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(CHOPPER)
        self.pushButton.setGeometry(QtCore.QRect(30, 360, 211, 51))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(CHOPPER)
        self.comboBox.setGeometry(QtCore.QRect(100, 110, 61, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(CHOPPER)
        self.label_3.setGeometry(QtCore.QRect(114, 85, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(CHOPPER)
        self.label_4.setGeometry(QtCore.QRect(104, 150, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(CHOPPER)
        self.label_6.setGeometry(QtCore.QRect(116, 280, 60, 16))
        self.label_6.setObjectName("label_6")
        self.checkBox_2 = QtWidgets.QCheckBox(CHOPPER)
        self.checkBox_2.setGeometry(QtCore.QRect(142, 240, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_5 = QtWidgets.QLabel(CHOPPER)
        self.label_5.setGeometry(QtCore.QRect(102, 215, 55, 16))
        self.label_5.setObjectName("label_5")
        self.checkBox = QtWidgets.QCheckBox(CHOPPER)
        self.checkBox.setGeometry(QtCore.QRect(92, 240, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.label_7 = QtWidgets.QLabel(CHOPPER)
        self.label_7.setGeometry(QtCore.QRect(978, 44, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.radioButton_13 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_13.setGeometry(QtCore.QRect(890, 434, 321, 20))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_14.setGeometry(QtCore.QRect(890, 494, 351, 20))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_19 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_19.setGeometry(QtCore.QRect(890, 524, 311, 20))
        self.radioButton_19.setObjectName("radioButton_19")
        self.radioButton_21 = QtWidgets.QRadioButton(CHOPPER)
        self.radioButton_21.setGeometry(QtCore.QRect(890, 464, 361, 21))
        self.radioButton_21.setObjectName("radioButton_21")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(CHOPPER)
        self.plainTextEdit.setGeometry(QtCore.QRect(86, 300, 91, 31))
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(CHOPPER)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(84, 170, 91, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(CHOPPER)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(270, 70, 591, 501))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(CHOPPER)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(270, 630, 591, 201))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")

        self.retranslateUi(CHOPPER)
        QtCore.QMetaObject.connectSlotsByName(CHOPPER)

    def retranslateUi(self, CHOPPER):
        _translate = QtCore.QCoreApplication.translate
        CHOPPER.setWindowTitle(_translate("CHOPPER", "Dialog"))
        self.radioButton.setText(_translate("CHOPPER", "ОСНОВНЫЕ ПАРАМЕТРЫ ДЛЯ УПРАВЛЕНИЯ И ИНДИКАЦИИ "))
        self.radioButton_2.setText(_translate("CHOPPER", "КАЧЕСТВО РАБОТЫ ПРЕРЫВАТЕЛЯ"))
        self.radioButton_3.setText(_translate("CHOPPER", "КАЧЕСТВО РАБОТЫ ПРЕРЫВАТЕЛЯ"))
        self.radioButton_4.setText(_translate("CHOPPER", "ПАРАМЕТРЫ РЕАКТОРА"))
        self.radioButton_5.setText(_translate("CHOPPER", "КАЧЕСТВО СЕЛЕКТОРНЫХ ИМПУЛЬСОВ"))
        self.radioButton_6.setText(_translate("CHOPPER", "PID-P РАССОГЛАСОВАНИЕ"))
        self.radioButton_7.setText(_translate("CHOPPER", "ПАРАМЕТРЫ ТОЛЧКОВ ДЛЯ ПОИСКА ОКНА"))
        self.radioButton_8.setText(_translate("CHOPPER", "ПАРАМЕТРЫ ФИЛЬТРАЦИИ ПОМЕХ"))
        self.radioButton_9.setText(_translate("CHOPPER", "БЛОК ИНФОРМАЦИИ ПЕРЕСЧЕТА СТАРТОВ И СЕЛЕКТОРОВ"))
        self.radioButton_10.setText(_translate("CHOPPER", "КАЧЕСТВО ФАЗИРОВКИ "))
        self.radioButton_11.setText(_translate("CHOPPER", "СПЕЦИАЛЬНЫЙ КОНТРОЛЬ"))
        self.radioButton_12.setText(_translate("CHOPPER", "КАЧЕСТВО ВЫХОДА (УПРАВ. СИГН.).."))
        self.label.setText(_translate("CHOPPER", "STATYS"))
        self.label_2.setText(_translate("CHOPPER", "DATA"))
        self.pushButton.setText(_translate("CHOPPER", "SEND"))
        self.label_3.setText(_translate("CHOPPER", "COM"))
        self.label_4.setText(_translate("CHOPPER", "№ Block"))
        self.label_6.setText(_translate("CHOPPER", "DATA"))
        self.checkBox_2.setText(_translate("CHOPPER", "W"))
        self.label_5.setText(_translate("CHOPPER", "Attribytes"))
        self.checkBox.setText(_translate("CHOPPER", "R"))
        self.label_7.setText(_translate("CHOPPER", "CATEGORIES"))
        self.radioButton_13.setText(_translate("CHOPPER", "ПАРАМЕТРЫ РАЗГОНА"))
        self.radioButton_14.setText(_translate("CHOPPER", "СБОЙ = ПРИ РЕЗКОМ ИЗМЕНЕНИИ ФАЗЫ БОЛЕЕ ЧЕМ НА 200 мкс"))
        self.radioButton_19.setText(_translate("CHOPPER", "СБОЙ = ВЫХОД ИЗ СТАБ.ФАЗЫ В РЕЖИМ СТАБ.ПЕРИОДА"))
        self.radioButton_21.setText(_translate("CHOPPER", "БЛОК ИНФОРМАЦИИ ПРИ ВЫХОДЕ ИЗ ДИАПАЗОНА СТАБИЛИЗАЦИИ "))
        self.plainTextEdit.setPlaceholderText(_translate("CHOPPER", "0000"))
        self.plainTextEdit_2.setPlaceholderText(_translate("CHOPPER", "0"))
        self.plainTextEdit_3.setPlaceholderText(_translate("CHOPPER", "response.."))
        self.plainTextEdit_4.setPlaceholderText(_translate("CHOPPER", "status.."))
